/**
 * manager.js — the test-session manager page.
 *
 * Reads the changesets out of `chrome.storage.local`, renders them, and asks an
 * Adminer tab to run a rollback. It never fetches Adminer itself: from this
 * page's origin such a request is cross-site, and the PHP session cookie — Lax
 * by default — would simply not be attached, so the fetch would come back as the
 * login screen and be parsed as "no rows". Delegating to the tab keeps every
 * request same-origin, which is also the only place the CSRF token is valid.
 *
 * Statement text shown here is generated by the same `undo.js` the rollback
 * runs, so the preview cannot drift from what actually executes.
 *
 * This file boots the page and wires its controls; drawing, the buttons'
 * actions, the dialogs and the page state are in manager/.
 */

import { THEME_KEY } from '../shared/storage-keys.js';
import { getLang, setLang, t } from './i18n.js';
import { cleanup, exportJson, exportSql, openSettings, redoSelected, removeSession, rename, rollbackSelected, toggleOpen } from './manager/actions.js';
import { render, renderRail } from './manager/render.js';
import { el, managerState, ui } from './manager/state.js';
import * as store from './session.js';

/* === Boot ════════════════════════════════════════════════════════════════ */

init();

async function init() {
  for (const id of [
    'sessionList', 'detailHead', 'sessName', 'sessMeta', 'sessState', 'changeList', 'changeHead',
    'changeCount', 'chkAll', 'report', 'btnRollback', 'btnRedo', 'btnExportSql', 'btnExportJson', 'btnRename',
    'btnToggleOpen', 'btnDelete', 'btnSettings', 'btnLang', 'langLabel', 'settingsDlg', 'toast', 'extras',
    'railFilter', 'btnCleanup',
  ]) ui[id] = el(id);

  managerState.settings = await store.getSettings();
  setLang(managerState.settings.lang);
  applyTheme();
  paintStatic();
  wire();

  await reload();
  const first = target();
  select(first.session && managerState.sessions[first.session] ? first.session : newestId());
  if (first.change) focusChange(first.change);
  if (new URLSearchParams(location.search).has('settings')) openSettings();

  // "View" on the panel reuses this tab and says which session through the hash.
  window.addEventListener('hashchange', () => {
    const next = target();
    if (next.session && managerState.sessions[next.session]) select(next.session);
    if (next.change) focusChange(next.change);
  });

  chrome.storage.onChanged.addListener((changes, area) => {
    if (area === 'local' && changes.dbtoolsSessions) reload().then(() => render());
    // An Adminer tab remembers the preview's last choice in the settings; without
    // this, saving the settings dialog here would write the stale one back.
    if (area === 'local' && changes.dbtoolsSettings) store.getSettings().then((next) => { managerState.settings = next; });
  });
}

/**
 * The popup's theme, read the way the popup reads it (popup/theme.js): unset is
 * light, not the OS's choice, or this page came up dark beside a light popup.
 * Toggling it in the popup repaints an open manager tab straight away.
 */
function applyTheme() {
  const paint = (value) => document.documentElement.setAttribute('data-theme', value === 'dark' ? 'dark' : 'light');
  chrome.storage.local.get([THEME_KEY], (res) => paint(res[THEME_KEY]));
  chrome.storage.onChanged.addListener((changes, area) => {
    if (area === 'local' && changes[THEME_KEY]) paint(changes[THEME_KEY].newValue);
  });
}

/** Fill every `data-i18n` node — the page ships with empty ones. */
function paintStatic() {
  for (const node of document.querySelectorAll('[data-i18n]')) {
    node.textContent = t(node.dataset.i18n);
  }
  ui.langLabel.textContent = getLang().toUpperCase();
  ui.railFilter.placeholder = t('mgr.filter');
  ui.btnCleanup.title = t('mgr.cleanupHint');
  document.title = t('mgr.title');
}

function wire() {
  ui.btnLang.addEventListener('click', async () => {
    const next = getLang() === 'vi' ? 'en' : 'vi';
    setLang(next);
    managerState.settings = await store.setSettings({ lang: next, langChosen: true });
    paintStatic();
    render();
  });

  ui.btnSettings.addEventListener('click', () => openSettings());
  ui.railFilter.addEventListener('input', () => renderRail());
  ui.btnCleanup.addEventListener('click', cleanup);
  ui.chkAll.addEventListener('change', () => {
    const session = managerState.sessions[managerState.currentId];
    if (!session) return;
    managerState.selected = ui.chkAll.checked ? new Set(session.changes.map((c) => c.id)) : new Set();
    render();
  });

  ui.btnRollback.addEventListener('click', rollbackSelected);
  ui.btnRedo.addEventListener('click', redoSelected);
  ui.btnExportSql.addEventListener('click', exportSql);
  ui.btnExportJson.addEventListener('click', exportJson);
  ui.btnRename.addEventListener('click', rename);
  ui.btnToggleOpen.addEventListener('click', toggleOpen);
  ui.btnDelete.addEventListener('click', removeSession);
}

/** The session (and change) asked for — in the hash when this tab was reused, else in the query. */
function target() {
  const hash = new URLSearchParams(location.hash.slice(1));
  const query = new URLSearchParams(location.search);
  return {
    session: hash.get('session') || query.get('session') || '',
    change: hash.get('change') || query.get('change') || '',
  };
}

export function newestId() {
  return Object.values(managerState.sessions)
    .sort((a, b) => String(b.startedAt).localeCompare(String(a.startedAt)))
    .map((s) => s.id)[0] || '';
}

/** Open one change's diff, bring it into view and flash it — a recorded line clicked in the panel's log. */
function focusChange(changeId) {
  const session = managerState.sessions[managerState.currentId];
  if (!session || !session.changes.some((c) => c.id === changeId)) return;
  managerState.openIds.add(changeId);
  render();
  const node = ui.changeList.querySelector(`details[data-id="${CSS.escape(changeId)}"]`);
  if (!node) return;
  node.scrollIntoView({ block: 'center' });
  node.classList.add('flash');
  const FLASH_MS = 1600; // how long the change jumped to stays outlined
  setTimeout(() => node.classList.remove('flash'), FLASH_MS);
}

export async function reload() {
  managerState.sessions = await store.allSessions();
  return managerState.sessions;
}

export function select(id) {
  managerState.currentId = id;
  managerState.selected = new Set();
  managerState.openIds = new Set();
  // A report belongs to the session it was about.
  ui.report.hidden = true;
  render();
}
