/**
 * manager.js — the test-session manager page.
 *
 * Reads the changesets out of `chrome.storage.local`, renders them, and asks an
 * Adminer tab to run a rollback. It never fetches Adminer itself: from this
 * page's origin such a request is cross-site, and the PHP session cookie — Lax
 * by default — would simply not be attached, so the fetch would come back as the
 * login screen and be parsed as "no rows". Delegating to the tab keeps every
 * request same-origin, which is also the only place the CSRF token is valid.
 *
 * Statement text shown here is generated by the same `undo.js` the rollback
 * runs, so the preview cannot drift from what actually executes.
 */

import * as store from './session.js';
import { sessionUndoScript, blockingReason, redoBlockingReason, columnsToRestore } from './undo.js';
import { compactUndoScript } from './compact.js';
import { backupRestoreSql } from './snapshot.js';
import { joinStatements, engineOf } from './sqlquote.js';
import { connLabel, buildUrl } from './params.js';
import { rowKeyLabel, cleanupCandidates } from './summary.js';
import { t, setLang, getLang } from './i18n.js';
import { TABLE_COPIES } from './features.js';

const THEME_KEY = 'popupTheme';

const el = (id) => document.getElementById(id);
const ui = {};
let sessions = {};
let currentId = '';
let selected = new Set();
// Which changes have their diff open. The page redraws on every write to storage
// — which, with Adminer open beside it, is every recorded edit — and a redraw
// that shut every diff somebody had opened to read made the page unusable while
// the test was running.
let openIds = new Set();
let settings = null;

/* === Boot ════════════════════════════════════════════════════════════════ */

init();

async function init() {
  for (const id of [
    'sessionList', 'detailHead', 'sessName', 'sessMeta', 'sessState', 'changeList', 'changeHead',
    'changeCount', 'chkAll', 'report', 'btnRollback', 'btnRedo', 'btnExportSql', 'btnExportJson', 'btnRename',
    'btnToggleOpen', 'btnDelete', 'btnSettings', 'btnLang', 'langLabel', 'settingsDlg', 'toast', 'extras',
    'railFilter', 'btnCleanup',
  ]) ui[id] = el(id);

  settings = await store.getSettings();
  setLang(settings.lang);
  applyTheme();
  paintStatic();
  wire();

  await reload();
  const first = target();
  select(first.session && sessions[first.session] ? first.session : newestId());
  if (first.change) focusChange(first.change);
  if (new URLSearchParams(location.search).has('settings')) openSettings();

  // "View" on the panel reuses this tab and says which session through the hash.
  window.addEventListener('hashchange', () => {
    const next = target();
    if (next.session && sessions[next.session]) select(next.session);
    if (next.change) focusChange(next.change);
  });

  chrome.storage.onChanged.addListener((changes, area) => {
    if (area === 'local' && changes.dbtoolsSessions) reload().then(() => render());
    // An Adminer tab remembers the preview's last choice in the settings; without
    // this, saving the settings dialog here would write the stale one back.
    if (area === 'local' && changes.dbtoolsSettings) store.getSettings().then((next) => { settings = next; });
  });
}

/**
 * The popup's theme, read the way the popup reads it (popup/theme.js): unset is
 * light, not the OS's choice, or this page came up dark beside a light popup.
 * Toggling it in the popup repaints an open manager tab straight away.
 */
function applyTheme() {
  const paint = (value) => document.documentElement.setAttribute('data-theme', value === 'dark' ? 'dark' : 'light');
  chrome.storage.local.get([THEME_KEY], (res) => paint(res[THEME_KEY]));
  chrome.storage.onChanged.addListener((changes, area) => {
    if (area === 'local' && changes[THEME_KEY]) paint(changes[THEME_KEY].newValue);
  });
}

/** Fill every `data-i18n` node — the page ships with empty ones. */
function paintStatic() {
  for (const node of document.querySelectorAll('[data-i18n]')) {
    node.textContent = t(node.dataset.i18n);
  }
  ui.langLabel.textContent = getLang().toUpperCase();
  ui.railFilter.placeholder = t('mgr.filter');
  ui.btnCleanup.title = t('mgr.cleanupHint');
  document.title = t('mgr.title');
}

function wire() {
  ui.btnLang.addEventListener('click', async () => {
    const next = getLang() === 'vi' ? 'en' : 'vi';
    setLang(next);
    settings = await store.setSettings({ lang: next, langChosen: true });
    paintStatic();
    render();
  });

  ui.btnSettings.addEventListener('click', () => openSettings());
  ui.railFilter.addEventListener('input', () => renderRail());
  ui.btnCleanup.addEventListener('click', cleanup);
  ui.chkAll.addEventListener('change', () => {
    const session = sessions[currentId];
    if (!session) return;
    selected = ui.chkAll.checked ? new Set(session.changes.map((c) => c.id)) : new Set();
    render();
  });

  ui.btnRollback.addEventListener('click', rollbackSelected);
  ui.btnRedo.addEventListener('click', redoSelected);
  ui.btnExportSql.addEventListener('click', exportSql);
  ui.btnExportJson.addEventListener('click', exportJson);
  ui.btnRename.addEventListener('click', rename);
  ui.btnToggleOpen.addEventListener('click', toggleOpen);
  ui.btnDelete.addEventListener('click', removeSession);
}

/** The session (and change) asked for — in the hash when this tab was reused, else in the query. */
function target() {
  const hash = new URLSearchParams(location.hash.slice(1));
  const query = new URLSearchParams(location.search);
  return {
    session: hash.get('session') || query.get('session') || '',
    change: hash.get('change') || query.get('change') || '',
  };
}

function newestId() {
  return Object.values(sessions)
    .sort((a, b) => String(b.startedAt).localeCompare(String(a.startedAt)))
    .map((s) => s.id)[0] || '';
}

/** Open one change's diff, bring it into view and flash it — a recorded line clicked in the panel's log. */
function focusChange(changeId) {
  const session = sessions[currentId];
  if (!session || !session.changes.some((c) => c.id === changeId)) return;
  openIds.add(changeId);
  render();
  const node = ui.changeList.querySelector(`details[data-id="${CSS.escape(changeId)}"]`);
  if (!node) return;
  node.scrollIntoView({ block: 'center' });
  node.classList.add('flash');
  setTimeout(() => node.classList.remove('flash'), 1600);
}

async function reload() {
  sessions = await store.allSessions();
  return sessions;
}

function select(id) {
  currentId = id;
  selected = new Set();
  openIds = new Set();
  // A report belongs to the session it was about.
  ui.report.hidden = true;
  render();
}

/* === Rendering ═══════════════════════════════════════════════════════════ */

function render() {
  renderRail();
  const session = sessions[currentId];

  ui.detailHead.hidden = !session;
  ui.changeHead.hidden = !session;
  renderExtras(session);
  if (!session) {
    // "Pick a session on the left" is only useful when there is one. With none,
    // this page is the first thing somebody opens from the popup, and what it
    // owes them is the four steps — none of which happen on this page.
    ui.changeList.replaceChildren(Object.keys(sessions).length ? para(t('mgr.noPreview')) : emptyHelp());
    return;
  }

  ui.sessName.textContent = session.name;
  ui.sessState.textContent = (session.closedAt ? t('mgr.closed') : t('mgr.open'))
    + (session.guard ? ` · ${t('mgr.playback')}` : '');
  ui.sessState.className = `pill${session.closedAt ? '' : ' open'}`;
  // The whole changeset, undone or not — it can be rolled back again.
  ui.sessMeta.textContent =
    `${connLabel(session.conn)} · ${new Date(session.startedAt).toLocaleString()} · `
    + `${t('panel.changes', { n: session.changes.length })}`;
  ui.btnToggleOpen.textContent = session.closedAt ? t('mgr.reopen') : t('mgr.close');
  ui.changeCount.textContent = t('mgr.pendingOf', {
    n: session.changes.filter((c) => !c.undone).length, total: session.changes.length,
  });
  paintRunButtons();

  const list = [...session.changes].sort((a, b) => b.seq - a.seq);
  ui.changeList.replaceChildren(...(list.length ? list.map(renderChange) : [para(t('mgr.empty'))]));
}

/**
 * Say what the buttons are about to do, not what they are called.
 *
 * With nothing ticked, rollback rolls the whole session back — it was still
 * labelled "Roll back selected", which reads as "nothing is selected, so this is
 * safe". It is the opposite: that is the widest thing this page can do.
 *
 * Re-apply counts the changes that were rolled back, because those are the ones
 * it would run; only when none were does it offer the whole session, which is
 * then a request to write the recorded values over what is there now.
 */
function paintRunButtons() {
  const session = sessions[currentId];
  if (!session) return;
  const ticked = session.changes.filter((c) => selected.has(c.id));
  ui.btnRollback.textContent = ticked.length
    ? t(ticked.some((c) => c.undone) ? 'mgr.rollbackAgainN' : 'mgr.rollbackN', { n: ticked.length })
    : t('mgr.rollbackAllN', { n: session.changes.length });
  // A session can be rolled back more than once, so the button stays available
  // while it holds anything at all.
  ui.btnRollback.disabled = !session.changes.length && !(TABLE_COPIES && (session.snapshots || []).length);

  const rolledBack = session.changes.filter((c) => c.undone).length;
  ui.btnRedo.textContent = ticked.length
    ? t('mgr.redoN', { n: ticked.length })
    : t('mgr.redoAllN', { n: rolledBack || session.changes.length });
  ui.btnRedo.disabled = !session.changes.length;

  ui.chkAll.checked = Boolean(session.changes.length) && ticked.length === session.changes.length;
}

function renderRail() {
  const all = Object.values(sessions)
    .sort((a, b) => String(b.startedAt).localeCompare(String(a.startedAt)));
  if (!all.length) {
    ui.railFilter.hidden = true;
    ui.sessionList.replaceChildren(para(t('mgr.empty')));
    return;
  }
  // A filter once there are enough sessions to lose one in; below that it is a box
  // in the way. Name or database, since two runs of one test share a name.
  ui.railFilter.hidden = all.length < 6;
  const q = ui.railFilter.hidden ? '' : ui.railFilter.value.trim().toLowerCase();
  const entries = q
    ? all.filter((s) => `${s.name} ${connLabel(s.conn)}`.toLowerCase().includes(q))
    : all;
  if (!entries.length) {
    ui.sessionList.replaceChildren(para(t('panel.pickNone')));
    return;
  }
  ui.sessionList.replaceChildren(...entries.map((session) => {
    const button = document.createElement('button');
    button.className = `sess${session.id === currentId ? ' active' : ''}`;
    button.innerHTML = '<span class="t"></span><span class="s"></span>';
    const title = button.querySelector('.t');
    title.textContent = session.name;
    // The one recording is the one somebody is usually looking for; "Closed" on
    // every other row said the same thing thirty times and marked nothing.
    if (!session.closedAt) {
      const rec = document.createElement('span');
      rec.className = 'rec';
      rec.textContent = t('mgr.recording');
      title.append(rec);
    }
    // Opened by a Playback run rather than by hand — usually rolled back already,
    // and not what someone scanning for their own test is looking for.
    if (session.guard) {
      const tag = document.createElement('span');
      tag.className = 'tag';
      tag.textContent = t('mgr.playback');
      title.append(tag);
    }
    button.querySelector('.s').textContent =
      `${connLabel(session.conn)} · ${t('panel.changes', { n: session.changes.length })} · ${shortDate(session.startedAt)}`;
    button.addEventListener('click', () => select(session.id));
    return button;
  }));
}

function shortDate(iso) {
  try {
    return new Date(iso).toLocaleString(undefined, { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' });
  } catch {
    return String(iso || '');
  }
}

/**
 * Snapshots and backup tables of the selected session. Both are acted on by an
 * Adminer tab, like the rollback — this page only shows them and asks.
 */
function renderExtras(session) {
  const snaps = (session && session.snapshots) || [];
  const backups = (session && session.backups) || [];
  ui.extras.hidden = !TABLE_COPIES || !session || (!snaps.length && !backups.length);
  if (ui.extras.hidden) {
    ui.extras.replaceChildren();
    return;
  }
  const blocks = [];
  if (snaps.length) {
    blocks.push(extraBlock(t('mgr.snapshots'), snaps.map((snap) => extraRow(
      snap.table,
      `${t('mgr.rows', { n: snap.rowCount })} · ${new Date(snap.takenAt).toLocaleString()}`
        + (snap.restoredAt ? ` · ${t('mgr.restored')}` : ''),
      [
        smallButton(t('mgr.restore'), () => askTab(session,
          { type: 'dbtools-snapshot-restore', sessionId: session.id, snapIds: [snap.id] })),
        smallButton(t('mgr.remove'), async () => {
          await store.removeSnapshot(session.id, snap.id);
          await reload();
          render();
        }),
      ],
    ))));
  }
  if (backups.length) {
    const engine = engineOf(session.conn && session.conn.driver);
    blocks.push(extraBlock(t('mgr.backups'), backups.map((bk) => extraRow(
      `${bk.table} → ${bk.backup}`,
      new Date(bk.createdAt).toLocaleString()
        + (bk.restoredAt ? ` · ${t('mgr.restored')}` : '')
        + (bk.droppedAt ? ` · ${t('mgr.dropped')}` : ''),
      bk.droppedAt ? [] : [
        smallButton(t('mgr.restore'), () => askTab(session,
          { type: 'dbtools-backup-restore', sessionId: session.id, backupId: bk.id })),
        smallButton(t('mgr.copySql'), async () => {
          const sql = joinStatements(backupRestoreSql(bk.table, bk.backup, bk.engine || engine));
          try {
            await navigator.clipboard.writeText(sql);
            toast(t('rollback.copied'));
          } catch {
            toast(sql);
          }
        }),
        smallButton(t('mgr.drop'), () => askTab(session,
          { type: 'dbtools-backup-drop', sessionId: session.id, backupId: bk.id }), 'danger-outline'),
      ],
    ))));
  }
  ui.extras.replaceChildren(...blocks);
}

function extraBlock(title, rows) {
  const box = document.createElement('section');
  box.className = 'extra';
  const h = document.createElement('h3');
  h.textContent = title;
  box.append(h, ...rows);
  return box;
}

function extraRow(name, meta, actions) {
  const row = document.createElement('div');
  row.className = 'extra-row';
  const n = document.createElement('span');
  n.className = 'tbl';
  n.textContent = name;
  const m = document.createElement('span');
  m.className = 'meta grow';
  m.textContent = meta;
  row.append(n, m, ...actions.filter(Boolean));
  return row;
}

function smallButton(label, onClick, cls = '') {
  return makeButton(label, onClick, `small ${cls}`.trim());
}

function makeButton(label, onClick, cls = '') {
  const b = document.createElement('button');
  b.className = `btn ${cls}`.trim();
  b.textContent = label;
  b.addEventListener('click', onClick);
  return b;
}

function renderChange(change) {
  const details = document.createElement('details');
  details.className = `change${change.undone ? ' undone' : ''}`;
  details.dataset.id = change.id;
  details.open = openIds.has(change.id);
  details.addEventListener('toggle', () => {
    if (details.open) openIds.add(change.id); else openIds.delete(change.id);
  });

  const summary = document.createElement('summary');
  const box = document.createElement('input');
  box.type = 'checkbox';
  box.checked = selected.has(change.id);
  box.addEventListener('click', (e) => e.stopPropagation());
  box.addEventListener('change', () => {
    if (box.checked) selected.add(change.id); else selected.delete(change.id);
    // Only the buttons: a full re-render here would shut every diff the person has
    // opened to decide what to tick.
    paintRunButtons();
  });

  const op = document.createElement('span');
  op.className = `op ${change.op}`;
  op.textContent = t(`op.${change.op}`);

  const table = document.createElement('span');
  table.className = 'tbl';
  table.textContent = change.table || '?';

  // Which row, before how many: two UPDATEs of one table were told apart only
  // by their time until one was opened.
  const key = document.createElement('span');
  key.className = 'key';
  key.textContent = rowKeyLabel(change);

  const meta = document.createElement('span');
  meta.className = 'meta grow';
  const rows = (change.rows || []).length;
  meta.textContent = `${t('mgr.rows', { n: rows })} · ${new Date(change.at).toLocaleTimeString()}` +
    (change.verified === false ? ` · ${t('mgr.unverified')}` : '') +
    (change.undone ? ` · ${t('mgr.undone')}` : '');

  summary.append(box, op, table);
  if (key.textContent) summary.append(key);
  summary.append(meta);

  const reason = blockingReason(change);
  if (reason) {
    const warn = document.createElement('span');
    warn.className = 'warn';
    warn.textContent = `⚠ ${t(`reason.${reason}`)}`;
    summary.append(warn);
  }

  // Undo just this one, without ticking it and reaching for the button at the
  // top. A change that cannot be undone gets no button to press for nothing.
  if (!reason) {
    const undo = document.createElement('button');
    undo.className = 'btn small undo-one';
    undo.textContent = change.undone ? t('mgr.againOne') : t('mgr.undoOne');
    undo.title = change.undone ? t('mgr.againOneHint') : t('mgr.undoOneHint');
    undo.addEventListener('click', (e) => {
      // Inside a <summary>: without this the click also opens or shuts the diff.
      e.preventDefault();
      e.stopPropagation();
      rollbackOne(change);
    });
    summary.append(undo);
  }

  // And put this one back the way the test had it — offered once it has been
  // rolled back, which is the only time there is anything to re-apply.
  if (change.undone && !redoBlockingReason(change)) {
    const again = document.createElement('button');
    again.className = 'btn small redo-one';
    again.textContent = t('mgr.redoOne');
    again.title = t('mgr.redoOneHint');
    again.addEventListener('click', (e) => {
      e.preventDefault();
      e.stopPropagation();
      redoOne(change);
    });
    summary.append(again);
  }
  details.append(summary);

  const body = document.createElement('div');
  body.className = 'change-body';
  if (change.statement) {
    const pre = document.createElement('pre');
    pre.className = 'sql';
    pre.textContent = change.statement;
    body.append(pre);
  }
  for (const row of change.rows || []) body.append(renderRow(change, row));
  if ((change.warnings || []).length) {
    const warn = document.createElement('div');
    warn.className = 'warn';
    warn.textContent = `${t('mgr.warnings')}: ${change.warnings.join(', ')}`;
    body.append(warn);
  }
  details.append(body);
  return details;
}

function renderRow(change, row) {
  const table = document.createElement('table');
  table.className = 'diff';
  const head = document.createElement('tr');
  for (const label of [t('mgr.column'), t('mgr.before'), t('mgr.after')]) {
    const th = document.createElement('th');
    th.textContent = label;
    head.append(th);
  }
  table.append(head);

  const caption = document.createElement('caption');
  caption.className = 'meta';
  caption.style.textAlign = 'left';
  caption.textContent = Object.entries(row.where || {})
    .map(([col, value]) => `${col}=${value === null ? 'NULL' : value}`).join(', ') || '—';
  table.prepend(caption);

  const cols = change.op === 'delete'
    ? Object.keys(row.before || {})
    : (change.op === 'insert' ? Object.keys(row.after || {}) : columnsToRestore(change, row));

  for (const col of cols) {
    const tr = document.createElement('tr');
    const name = document.createElement('td');
    name.textContent = col;
    tr.append(name, cell(row.before && row.before[col], 'before'), cell(row.after && row.after[col], 'after'));
    table.append(tr);
  }
  return table;
}

function cell(value, cls) {
  const td = document.createElement('td');
  td.className = `val ${cls}`;
  if (value === null || value === undefined) {
    const i = document.createElement('span');
    i.className = 'null';
    i.textContent = 'NULL';
    td.append(i);
  } else {
    td.textContent = value;
  }
  return td;
}

function para(text) {
  const p = document.createElement('p');
  p.className = 'empty';
  p.textContent = text;
  return p;
}

/** How to get a first session, for a page that has none. */
function emptyHelp() {
  const box = document.createElement('div');
  box.className = 'howto';
  const h = document.createElement('h3');
  h.textContent = t('mgr.emptyTitle');
  const steps = document.createElement('ol');
  for (const key of ['mgr.emptyStep1', 'mgr.emptyStep2', 'mgr.emptyStep3', 'mgr.emptyStep4']) {
    const li = document.createElement('li');
    li.textContent = t(key);
    steps.append(li);
  }
  box.append(h, steps);
  return box;
}

/* === Actions ═════════════════════════════════════════════════════════════ */

/**
 * Hand work to an Adminer tab on the session's origin — the one connected to the
 * session's database; a tab on another database of the same host answers
 * `wrongConn` and is passed over. Without one there is nothing that can run it,
 * and saying so beats a request that quietly comes back as the login page.
 *
 * The tab is brought to the front first: it shows the preview, and a preview in
 * a tab nobody is looking at would simply wait.
 */
async function askTab(session, message) {
  if (!settings.autoExecute) {
    showReport(t('mgr.autoExecuteOff'), 'err', { label: t('mgr.exportSql'), onClick: exportSql });
    return null;
  }
  const tabs = await chrome.tabs.query({ url: `${session.origin}/*` });
  if (!tabs.length) {
    showReport(t('mgr.needTab', { origin: session.origin }), 'err', openAdminerAction(session, message));
    return null;
  }
  let wrong = false;
  let off = false;
  try {
    for (const tab of tabs) {
      const ping = await chrome.tabs.sendMessage(tab.id, { type: 'dbtools-ping', key: session.key }, { frameId: 0 })
        .catch(() => null);
      if (!ping) continue;
      if (ping.wrongConn) {
        wrong = true;
        continue;
      }
      // Switched off, the tab has no panel to show the preview in and will refuse.
      if (ping.on === false) {
        off = true;
        continue;
      }
      // The preview opens over there, and this page goes to the background
      // mid-click. Saying so first means the tab switch is an answer to the
      // button, not something that just happened.
      showReport(t('mgr.handedOff'), '');
      await chrome.tabs.update(tab.id, { active: true });
      await chrome.windows.update(tab.windowId, { focused: true }).catch(() => {});
      const answer = await chrome.tabs.sendMessage(tab.id, message, { frameId: 0 });
      reportAnswer(answer);
      return answer;
    }
    // Every way this can fail comes with the one thing that fixes it, rather
    // than a sentence telling someone to go and do it elsewhere.
    if (off) {
      showReport(t('mgr.integrationOff'), 'err', {
        label: t('mgr.turnOn'),
        onClick: async () => {
          settings = await store.setSettings({ enabled: true });
          await new Promise((r) => setTimeout(r, 400));   // the tab switches itself on from storage
          await askTab(session, message);
        },
      });
    } else {
      showReport(t(wrong ? 'mgr.wrongConn' : 'mgr.needTab', { origin: session.origin }), 'err',
        openAdminerAction(session, message));
    }
    return null;
  } catch (err) {
    showReport(String(err && err.message || err), 'err');
    return null;
  } finally {
    await reload();
    render();
  }
}

/**
 * "Open Adminer": a tab on the session's own database, then — once its panel
 * answers — the same request again, so the rollback that was asked for carries
 * on instead of having to be asked for twice. It still stops at the preview.
 */
function openAdminerAction(session, message) {
  if (!session.base) return null;
  return {
    label: t('mgr.openAdminer'),
    onClick: async () => {
      const tab = await chrome.tabs.create({ url: buildUrl(session.base, session.conn || {}, {}), active: true });
      showReport(t('mgr.waitingAdminer'), '');
      if (await waitForPanel(tab.id, session.key, 60000)) await askTab(session, message);
      else showReport(t('mgr.adminerNotReady'), 'err', openAdminerAction(session, message));
    },
  };
}

/** Wait for an Adminer tab's panel to answer for this database — through a login, if it asks for one. */
async function waitForPanel(tabId, key, ms) {
  const until = Date.now() + ms;
  while (Date.now() < until) {
    const ping = await chrome.tabs.sendMessage(tabId, { type: 'dbtools-ping', key }, { frameId: 0 })
      .catch(() => null);
    if (ping && ping.ok && ping.on !== false) return true;
    if (!(await chrome.tabs.get(tabId).catch(() => null))) return false;   // closed
    await new Promise((r) => setTimeout(r, 700));
  }
  return false;
}

/** Say how it went, whichever kind of report came back. */
function reportAnswer(answer) {
  if (!answer || !answer.ok) {
    showReport(String((answer && answer.error) || 'failed'), 'err');
    return;
  }
  const r = answer.report || {};
  // Walking away from the preview is an answer; leaving "continue in the Adminer
  // tab" on screen would read as still waiting for one.
  if (r.cancelled) {
    showReport(t('mgr.cancelled'), '');
    return;
  }
  if (r.nothing) {
    showReport(t('rollback.nothing'), '');
    return;
  }
  // A backup restore or drop answers with a plain ok flag.
  if (typeof r.ok === 'boolean') {
    showReport(r.ok ? t('rollback.done', { ok: 1, fail: 0 }) : String(r.error || 'failed'), r.ok ? 'ok' : 'err');
    return;
  }
  // A rollback carries its snapshot restore inside; a snapshot restore is one.
  const snaps = 'tables' in r ? r : (r.snapshots || { ok: 0, failed: 0 });
  const main = 'tables' in r ? { ok: 0, failed: 0 } : r;
  const ok = (main.ok || 0) + (snaps.ok || 0);
  const fail = (main.failed || 0) + (snaps.failed || 0);
  // Changes it could not undo are the half of the outcome that used to go
  // unmentioned: "2 succeeded, 0 failed" reads as done, with three rows still
  // sitting there as the test left them.
  const skipped = main.skipped || 0;
  showReport(
    t('rollback.done', { ok, fail }) + (skipped ? ` ${t('rollback.skippedDone', { n: skipped })}` : ''),
    fail ? 'err' : (skipped ? 'warn' : 'ok'),
  );
}

async function rollbackOne(change) {
  const session = sessions[currentId];
  if (!session) return;
  await askTab(session, {
    type: 'dbtools-run-rollback',
    sessionId: session.id,
    changeIds: [change.id],
    includeUndone: Boolean(change.undone),
  });
}

async function rollbackSelected() {
  const session = sessions[currentId];
  if (!session) return;
  ui.btnRollback.disabled = true;
  const ticked = session.changes.filter((c) => selected.has(c.id));
  await askTab(session, {
    type: 'dbtools-run-rollback',
    sessionId: session.id,
    // Nothing ticked means everything: the change log and the snapshots.
    changeIds: selected.size ? [...selected] : undefined,
    // Ticking a change that was already undone is a request to run it again.
    includeUndone: ticked.some((c) => c.undone),
  });
  selected = new Set();
  render();
}

async function redoOne(change) {
  const session = sessions[currentId];
  if (!session) return;
  await askTab(session, {
    type: 'dbtools-run-redo',
    sessionId: session.id,
    changeIds: [change.id],
    includeApplied: !change.undone,
  });
}

async function redoSelected() {
  const session = sessions[currentId];
  if (!session) return;
  ui.btnRedo.disabled = true;
  const ticked = session.changes.filter((c) => selected.has(c.id));
  await askTab(session, {
    type: 'dbtools-run-redo',
    sessionId: session.id,
    // Nothing ticked means every change that was rolled back.
    changeIds: selected.size ? [...selected] : undefined,
    // Ticking a change that is still applied is a request to write its values again.
    includeApplied: ticked.some((c) => !c.undone),
  });
  selected = new Set();
  render();
}

function exportSql() {
  const session = sessions[currentId];
  if (!session) return;
  // Folded per row when that is how rollbacks are run (the preview's last choice,
  // or the setting): the file is then the same statements the preview shows.
  const statements = settings.compactRun ? compactUndoScript(session) : sessionUndoScript(session, {});
  if (!statements.length) return toast(t('rollback.nothing'));
  const header = `-- ${session.name}\n-- ${connLabel(session.conn)}\n-- ${new Date().toISOString()}\n\n`;
  download(`${slug(session.name)}-undo.sql`, header + joinStatements(statements), 'text/plain');
}

function exportJson() {
  const session = sessions[currentId];
  if (!session) return;
  const engine = engineOf(session.conn && session.conn.driver);
  download(`${slug(session.name)}-changeset.json`, JSON.stringify({ engine, ...session }, null, 2), 'application/json');
}

async function rename() {
  const session = sessions[currentId];
  if (!session) return;
  const name = await askDialog({
    title: t('mgr.rename'), label: t('mgr.sessionName'), value: session.name, confirmLabel: t('mgr.rename'),
  });
  if (name === null) return;
  await store.renameSession(session.id, name.trim() || session.name);
  await reload();
  render();
}

async function toggleOpen() {
  const session = sessions[currentId];
  if (!session) return;
  // Resuming ends whichever session was recording on that database — one at a
  // time — and the panel in its Adminer tab follows without a reload.
  if (session.closedAt) {
    await store.reopenSession(session.id);
    showReport(t('panel.resumed', { name: session.name }), 'ok');
  } else {
    await store.closeSession(session.id);
  }
  await reload();
  render();
}

async function removeSession() {
  const session = sessions[currentId];
  if (!session) return;
  const ok = await confirmDialog({
    title: t('mgr.delete'),
    text: `${session.name}\n${t('panel.changes', { n: session.changes.length })}`,
    confirmLabel: t('mgr.delete'),
  });
  if (!ok) return;
  await store.deleteSession(session.id);
  await reload();
  select(Object.keys(sessions)[0] || '');
}

/**
 * Delete ended sessions in one go.
 *
 * By default only the ones with nothing left to undo; the ones that still hold
 * changes are one tick away, and counted, so nobody deletes a session they
 * still needed by accident. Sessions that still own a backup table in the
 * database are never offered: this record is the only way back to it.
 */
async function cleanup() {
  const groups = cleanupCandidates(sessions);
  if (!groups.spent.length && !groups.pending.length) {
    toast(t('mgr.cleanupNone'));
    return;
  }
  const body = document.createElement('div');
  body.className = 'cleanup';
  const line = document.createElement('p');
  line.className = 'meta';
  line.textContent = t('mgr.cleanupSpent', { n: groups.spent.length });
  body.append(line);

  let includePending = null;
  if (groups.pending.length) {
    const label = document.createElement('label');
    label.className = 'check';
    includePending = document.createElement('input');
    includePending.type = 'checkbox';
    const text = document.createElement('span');
    text.textContent = t('mgr.cleanupPending', { n: groups.pending.length });
    label.append(includePending, text);
    body.append(label);
  }
  if (groups.keptForBackups.length) {
    const kept = document.createElement('p');
    kept.className = 'meta';
    kept.textContent = t('mgr.cleanupKept', { n: groups.keptForBackups.length });
    body.append(kept);
  }

  const count = () => groups.spent.length + (includePending && includePending.checked ? groups.pending.length : 0);
  const ok = await new Promise((resolve) => {
    let go = null;
    const paint = () => {
      go.textContent = t('mgr.cleanupGo', { n: count() });
      go.disabled = !count();
    };
    openDialog({
      title: t('mgr.cleanupTitle'),
      body,
      answer: (value) => resolve(value === true),
      buttons: (close) => {
        go = makeButton('', () => close(true), 'danger');
        return [makeButton(t('rollback.cancel'), () => close(false)), go];
      },
    });
    if (includePending) includePending.addEventListener('change', paint);
    paint();
  });
  if (!ok) return;

  const doomed = cleanupCandidates(sessions, {
    includePending: Boolean(includePending && includePending.checked),
  }).chosen;
  for (const session of doomed) await store.deleteSession(session.id);
  await reload();
  if (!sessions[currentId]) select(newestId()); else render();
  toast(t('mgr.cleanupDone', { n: doomed.length }));
}

async function openSettings() {
  el('setEnabled').checked = settings.enabled;
  el('setAutoExecute').checked = settings.autoExecute;
  el('setDrift').checked = settings.driftCheck;
  el('setCompact').checked = Boolean(settings.compactRun);
  el('setSqlPage').checked = settings.captureSqlPage;
  el('setLimit').value = settings.prefetchLimit;
  el('setSnapLimit').value = settings.snapshotLimit;
  // Held back (features.js): the fields stay in the form, so saving keeps the
  // stored values, but they are not offered.
  el('setSnapLimit').closest('label').hidden = !TABLE_COPIES;
  document.querySelector('fieldset.guard').hidden = !TABLE_COPIES;
  el('setKeyLimit').value = settings.keyScanLimit;
  el('setEngine').value = settings.engineOverride;

  // How much of chrome.storage.local the changesets take up, next to its cap.
  // Worth seeing: when this storage fills, every write fails — recording, ending
  // a session, everything — and the panel's buttons stop having any effect.
  // Snapshot rows are not counted: they live in IndexedDB (snapstore.js).
  el('storageUsed').textContent = '';
  if (chrome.storage.local.getBytesInUse) {
    chrome.storage.local.getBytesInUse(null, (bytes) => {
      void chrome.runtime.lastError;
      const quota = chrome.storage.local.QUOTA_BYTES || 5242880;
      el('storageUsed').textContent = t('mgr.storageUsed', {
        mb: (bytes / 1048576).toFixed(2),
        max: Math.round(quota / 1048576),
      });
    });
  }

  // The databases this browser has opened in Adminer: the guard works through a
  // tab on one of them, so it can only be pointed at one of them.
  const guard = { ...store.DEFAULT_SETTINGS.guard, ...(settings.guard || {}) };
  const res = await chrome.storage.local.get('dbtoolsConns');
  const conns = Object.values(res.dbtoolsConns || {});
  const pick = el('setGuardConn');
  pick.replaceChildren();
  if (!conns.length) pick.append(new Option(t('mgr.guardConnNone'), ''));
  for (const conn of conns) pick.append(new Option(conn.label, conn.key, false, conn.key === guard.key));
  el('setGuard').checked = guard.enabled;
  el('setGuardTables').value = (guard.tables || []).join(', ');
  el('setGuardAuto').checked = guard.autoRollback !== false;

  // Saved from the button, not from the dialog's `close` event: Chrome does not
  // fire that event for every way a dialog goes away, and settings that quietly
  // did not save are worse than none. `once` keeps Escape from saving twice.
  let saved = false;
  const save = async () => {
    if (saved) return;
    saved = true;
    const chosen = conns.find((c) => c.key === pick.value) || null;
    settings = await store.setSettings({
      enabled: el('setEnabled').checked,
      autoExecute: el('setAutoExecute').checked,
      driftCheck: el('setDrift').checked,
      compactRun: el('setCompact').checked,
      captureSqlPage: el('setSqlPage').checked,
      prefetchLimit: Math.max(1, Number(el('setLimit').value) || 200),
      snapshotLimit: Math.max(1, Number(el('setSnapLimit').value) || 5000),
      keyScanLimit: Math.max(1, Number(el('setKeyLimit').value) || 10000),
      engineOverride: el('setEngine').value,
      guard: {
        enabled: el('setGuard').checked && Boolean(chosen),
        key: chosen ? chosen.key : '',
        origin: chosen ? chosen.origin : '',
        label: chosen ? chosen.label : '',
        tables: el('setGuardTables').value.split(/[,;\s]+/).map((x) => x.trim()).filter(Boolean),
        autoRollback: el('setGuardAuto').checked,
      },
    });
  };

  el('setOk').addEventListener('click', save, { once: true });
  ui.settingsDlg.addEventListener('close', save, { once: true });
  ui.settingsDlg.addEventListener('cancel', save, { once: true });
  ui.settingsDlg.showModal();
}

/* === Asking ══════════════════════════════════════════════════════════════
 * Renaming a session and deleting one used to go through `prompt` and `confirm`.
 * Those belong to the browser: a bar at the top of the window, in the browser's
 * own styling, disowned from the page that asked. They are asked here instead, in
 * the same dialog the settings use — and the panel inside Adminer asks its own
 * questions in the sheet its previews use, so nothing is answered in a box that
 * looks like it came from somewhere else.
 * ═══════════════════════════════════════════════════════════════════════════ */

/**
 * Show a modal and hand back the one answer it is for.
 *
 * The dialog's own `close` event is not what settles it. Chrome does not fire
 * that event for a `close()` called from script — the dialog simply closes and
 * nothing hears about it — so every way out of this one (a button, Enter, Escape,
 * the backdrop) goes through `finish`, which closes it, takes it off the page and
 * answers exactly once.
 */
function openDialog({ title, body, answer, buttons }) {
  const dlg = document.createElement('dialog');
  dlg.className = 'dlg';
  const wrap = document.createElement('div');
  wrap.className = 'dlg-body';
  const heading = document.createElement('h2');
  heading.textContent = title;
  const foot = document.createElement('div');
  foot.className = 'dlg-foot';
  wrap.append(heading, body, foot);
  dlg.append(wrap);
  document.body.append(dlg);

  let done = false;
  const finish = (value) => {
    if (done) return;
    done = true;
    dlg.close();
    dlg.remove();
    answer(value);
  };

  foot.append(...buttons(finish));
  dlg.addEventListener('cancel', (e) => { e.preventDefault(); finish(undefined); });
  dlg.addEventListener('click', (e) => { if (e.target === dlg) finish(undefined); });
  dlg.showModal();
  return { dlg, finish };
}

/** One line of text, or null when dismissed. */
function askDialog({ title, label, value = '', confirmLabel }) {
  return new Promise((resolve) => {
    const field = document.createElement('label');
    field.className = 'field';
    const caption = document.createElement('span');
    caption.textContent = label;
    const input = document.createElement('input');
    input.type = 'text';
    input.value = value;
    field.append(caption, input);

    const { finish } = openDialog({
      title,
      body: field,
      answer: (text) => resolve(text === undefined ? null : text),
      buttons: (close) => [
        makeButton(t('rollback.cancel'), () => close(undefined)),
        makeButton(confirmLabel, () => close(input.value), 'primary'),
      ],
    });
    input.addEventListener('keydown', (e) => {
      if (e.key !== 'Enter') return;
      e.preventDefault();
      finish(input.value);
    });
    input.focus();
    input.select();
  });
}

/** Yes or no. */
function confirmDialog({ title, text, confirmLabel }) {
  return new Promise((resolve) => {
    const line = document.createElement('p');
    line.className = 'meta';
    line.style.whiteSpace = 'pre-wrap';
    line.textContent = text;
    openDialog({
      title,
      body: line,
      answer: (value) => resolve(value === true),
      buttons: (close) => [
        makeButton(t('rollback.cancel'), () => close(false)),
        makeButton(confirmLabel, () => close(true), 'danger'),
      ],
    });
  });
}

/* === Small helpers ═══════════════════════════════════════════════════════ */

function showReport(text, kind, action) {
  ui.report.hidden = false;
  ui.report.className = `report ${kind || ''}`;
  ui.report.replaceChildren(document.createTextNode(text));
  if (action) {
    const b = makeButton(action.label, () => action.onClick(), 'small report-action');
    ui.report.append(b);
  }
}

let toastTimer = 0;
function toast(text) {
  ui.toast.hidden = false;
  ui.toast.textContent = text;
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => { ui.toast.hidden = true; }, 2600);
}

function slug(name) {
  return String(name).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'session';
}

function download(filename, text, mime) {
  const url = URL.createObjectURL(new Blob([text], { type: mime }));
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
